FROM python:3.7-slim

RUN apt-get clean \
  && apt-get update \
  && apt-get install -y gcc build-essential libpq-dev

RUN pip3 install psycopg2

RUN apt-get --purge -y remove gcc build-essential \
  && apt-get -y autoremove
